version: '3.7'

services:
  redis:
    image: redis:6
  db:
    image: postgres:14
    restart: always
    env_file: ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: ./.env
    links:
      - db
      - redis
    ports:
      - '4000:4000'
    volumes:
      - ./src:/usr/src/app/src
      - ./migrations:/usr/src/app/migrations
  frontend:
    image: djelnar/nozomi-test
    ports:
      - '3000:3000'
    links:
      - backend